### ISSUE TITLE
Please make better docs for how to generate tide csv files

### ISSUE THREAD

**Issue by ddbuscombe** [kvos/CoastSat.slope#25]
We see the basic workflow is documented [here](https://github.com/kvos/CoastSat.slope/blob/master/example_slope_Cable_beach.ipynb) requires the follow files:

1. netcdf files downloaded from AVISO - this part is really straightforward using CyberDuck FTP, but (apparently like a lot of users) I couldn't figure it out via the website
2. 'ocean_tide.ini' - where is this file? It is not in the downloaded tar.xz file from AVISO. what should it include? do you have examples?
3. 'load_tide.ini' - where is this file? It is not in the downloaded tar.xz file from AVISO
4. Why not make  'ocean_tide.ini'  and 'load_tide.ini'  available through CoastSat or CoastSat.slope? I assume they are small files?

I'm also curious as to why this is only documented here in CoastSat.slope, not CoastSat - isn't this a necessary step for any location with a measurable tide? Therefore why is it only documented and implemented here in CoastSat.slope? 

(sorry for the newbie question, I still haven't gotten around to actually using CoastSat.slope, but we're trying to figure out how to wrap the functionality of vanilla CoastSat in CoastSeg while providing the user option to input slope and provide tide csv file)

thanks!

**Comment by ddbuscombe** [comment]
Update: I see an example file here on another docs page

https://github.com/kvos/CoastSat.slope/blob/19036237299127338ac3f1f622729780035407bd/doc/ini_file.JPG

And I found a readme on the FTP that explains the contents of the nc files:

"The tides database contains 34 tidal components for each tide product: 
2N2, Eps2, J1, K1, K2, L2, La2, M2, M3, M4, M6, M8, Mf, MKS2, Mm, MN4, 
MS4, MSf, MSqm, Mtm, Mu2, N2, N4, Nu2, O1, P1, Q1, R2, S1, S2, S4, Sa, Ssa, T2."

So, now I can understand your instructions ...  I can make the ini files .... should the 'ini' files list all 34 tidal constituents?

**Comment by ddbuscombe** [comment]
Remaining questions;

- [ ] why is this only documented here on coastsat.slope and not in coastsat? Is that potentially confusing for a new user? (I understand why CoastSat and CoastSat.slope are separate toolboxes, but not why tide correction is only documented in coastsat.slope, where it is not needed - it is only needed in CoastSat, no?)
- [ ] would it be useful if I wrote a little utility script that generated ini files from a list of nc files? The user would not need to make their own ini files manually
- [ ]  do all 34 constituents get used?
- [ ] what is 'ocean_tide' - how does one get it? what info does it contain that is not inside 'load_tide'

**Comment by kvos** [comment]
hey @dbuscombe-usgs , a lot of good questions as always. 

Both 'ocean_tide' and 'load_tide' are needed as the constituents are derived from satellite altimetry (WGS84 datum). The tide loading accounts for the fact that the Earth's surface is elastic and responds to the change in tide (weight of the water column). Never use 'ocean_tide_extrapolated'!

This documentation is very very outdated, no doubts about that. Fes2014 used to be on bitbucket and have the .ini files there with the entire folder structure so you just had to download the .nc files and store them in the right folder. Now they moved to GitHub and I just changed the link but I haven't checked what the new folder structure is and what's available. I can provide a copy of the .ini files. 

Initially I thought keeping CoastSat and CoastSat.slope separate would make it easier to maintain. I didn't want to ask CoastSat users to also install pyfes (there's already enough installation issues). Not sure about this anymore, with the pypi package that Sharon developed.

CoastSat.slope works well with modelled tides as it's a frequency domain algorithm, that's why I suggest to use Fes2014. Users of CoastSat can either use tide gauge data and measured slopes, or they have to follow Coastsat.slope documentation to get tides and slopes.

**Comment by ddbuscombe** [comment]
thanks for the response

'ocean_tide' is not included in the download I made from AVIOS. I can't progress until I have that data. I'll need to rethink tides for coastseg - this fes14 method is not sustainable as it stands

**Comment by ddbuscombe** [comment]
Also, a single page that explained all of this, in one place, would help a lot of new coastsat users like me
