### ISSUE TITLE
About the TR/tanβ<10 problem

### ISSUE THREAD

**Issue by ligiaft** [kvos/CoastSat.slope#28]
Hello @kvos! Firstly, I appreciate your work with the CoastSat and CoastSat.slope! I'm using these techniques in my master study about some beaches in the Brazilian south coastal. Here the tidal is microtide, my beaches have short backshore and they can be high slope. How can I know wether my results (with large confidence band) are affected by this metodology error or my imput datas are insufficient? Can I somehow identify the influence of this problem (TR/tanβ<10) on my results?

Here is an example of one of my results:
![GRANTTransect](https://github.com/kvos/CoastSat.slope/assets/134415992/8b99d440-602a-4455-8fc9-cbcdfcb5fe73)
![GRANTTimeSerie](https://github.com/kvos/CoastSat.slope/assets/134415992/cd815344-2dce-4dec-8171-6d325400e59e)
![GRANTTimestepDistribuition](https://github.com/kvos/CoastSat.slope/assets/134415992/2d8a7975-96c2-4328-872d-e5fd17b40b65)
![GRANTPowerSpectrum](https://github.com/kvos/CoastSat.slope/assets/134415992/4af8d0aa-df71-47d5-8a4e-926116849e6e)
![GRANTTidalPeakFrequency](https://github.com/kvos/CoastSat.slope/assets/134415992/c2a76f8f-13cc-40f4-ae15-5e16af063a42)
![GRANTEnergy](https://github.com/kvos/CoastSat.slope/assets/134415992/9984a043-c3ae-479f-a577-c8bc43cf559f)

**Comment by kvos** [comment]
hi @ligiaft , yes unfortunately your shoreline time-series don't have a lot of data and the resulting tidal signal in the shoreline time-series is very weak. If you cannot see a clear peak at the spring/neap tidal cycle (grey band) the method won't be able to estimate the slope accurately. That's why you are seing the very large error band, because it's not able to estimate the slope. What's the tidal range at the site and expected slope more or less? to get TR/tan(b) you just divide the two, so for example if you have 1m tidal range and 0.1 slope than you have a ratio of 10. I hope this helps
